/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorresRouteImport } from './routes/torres'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipasRouteImport } from './routes/equipas'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorresTorreIdRouteImport } from './routes/torres.$torreId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TorresRoute = TorresRouteImport.update({
  id: '/torres',
  path: '/torres',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipasRoute = EquipasRouteImport.update({
  id: '/equipas',
  path: '/equipas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorresTorreIdRoute = TorresTorreIdRouteImport.update({
  id: '/$torreId',
  path: '/$torreId',
  getParentRoute: () => TorresRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRoute
  '/equipas': typeof EquipasRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mcp': typeof McpRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/relatorios': typeof RelatoriosRoute
  '/torres': typeof TorresRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/torres/$torreId': typeof TorresTorreIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRoute
  '/equipas': typeof EquipasRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mcp': typeof McpRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/relatorios': typeof RelatoriosRoute
  '/torres': typeof TorresRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/torres/$torreId': typeof TorresTorreIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipamentos': typeof EquipamentosRoute
  '/equipas': typeof EquipasRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mcp': typeof McpRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/relatorios': typeof RelatoriosRoute
  '/torres': typeof TorresRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/torres/$torreId': typeof TorresTorreIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipamentos'
    | '/equipas'
    | '/login'
    | '/mapa'
    | '/mcp'
    | '/recuperar-password'
    | '/relatorios'
    | '/torres'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/torres/$torreId'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipamentos'
    | '/equipas'
    | '/login'
    | '/mapa'
    | '/mcp'
    | '/recuperar-password'
    | '/relatorios'
    | '/torres'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/torres/$torreId'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/equipamentos'
    | '/equipas'
    | '/login'
    | '/mapa'
    | '/mcp'
    | '/recuperar-password'
    | '/relatorios'
    | '/torres'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/torres/$torreId'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipamentosRoute: typeof EquipamentosRoute
  EquipasRoute: typeof EquipasRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  McpRoute: typeof McpRoute
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TorresRoute: typeof TorresRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torres': {
      id: '/torres'
      path: '/torres'
      fullPath: '/torres'
      preLoaderRoute: typeof TorresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipas': {
      id: '/equipas'
      path: '/equipas'
      fullPath: '/equipas'
      preLoaderRoute: typeof EquipasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torres/$torreId': {
      id: '/torres/$torreId'
      path: '/$torreId'
      fullPath: '/torres/$torreId'
      preLoaderRoute: typeof TorresTorreIdRouteImport
      parentRoute: typeof TorresRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TorresRouteChildren {
  TorresTorreIdRoute: typeof TorresTorreIdRoute
}

const TorresRouteChildren: TorresRouteChildren = {
  TorresTorreIdRoute: TorresTorreIdRoute,
}

const TorresRouteWithChildren =
  TorresRoute._addFileChildren(TorresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipamentosRoute: EquipamentosRoute,
  EquipasRoute: EquipasRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  McpRoute: McpRoute,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
  RelatoriosRoute: RelatoriosRoute,
  TorresRoute: TorresRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
